### ISSUE TITLE
Recruit UX Designer

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/mealscount-backend#19]
Find a UX designer for updating the landing page design / look & feel, as well as provide some look and feel and UX guidance on the data viz.

**Comment by nikolajbaer** [comment]
Specifically I think the next step would be to create a new updated styleguide / look & feel for the mealscount website.

The existing website, mealscount.com, has a basic theme to it, but perhaps we could clean this up a bit, come up with a color scheme and maybe a basic bootstrap or foundation theme.

The other piece is to put together a UX design for the "data visualization". This would be a part II following the initial UX design.

**Comment by artlung** [comment]
If you posted to the UX Speakeasy (based in San Diego) Slack or Twitter I suspect you could find an interested UX practitioner.

**Comment by carloslazo** [comment]
I can offer my help with UX. What I can do first is do a basic clean up of what we have right now and then plan something fancier.

**Comment by nikolajbaer** [comment]
Thanks everyone,

We are currently talking to people with UX Speakeasy about getting some help!
