### ISSUE TITLE
Research free compute time on AWS

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/mealscount-backend#23]
Abdul mentioned that we may be able to get free compute time on AWS.

This is the ticket to investigate that

**Comment by aaden2099** [comment]
So, I investigated the issue and it wasn't that we can get free AWS compute time but rather that Hobson has a GPU server which he has been kind enough to allow us to use for free.

**Comment by nikolajbaer** [comment]
Sounds great, I am going to close this issue
