### ISSUE TITLE
Make rates a drop-down for each grouping of rates by school.

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/mealscount-backend#60]
Current Fed Reimbursement rates are editable fiels, but really this is a set rate table, so this should just be a dropdown selection that triggers everything.

Rates / selections are available in CEP Calculator from USDA. 

This might be fine to do as a UI feature in the DistrictSummary edit, and leave all the under-the-hood bits as specific values.

**Comment by pmelendez2** [comment]
1.  Select a School District, select a school, Federal Reimbursement Rates are displayed on screen.
2.  At bottom of page, select Edit button, Federal Reimbursement Rates are displayed in an Editable form.
![FederalReimburesementRates](https://user-images.githubusercontent.com/33038363/88598496-4301a900-d01e-11ea-8340-785764634918.png)
![EditFederalReimbrsementRate](https://user-images.githubusercontent.com/33038363/88598500-44cb6c80-d01e-11ea-9ba9-63a4d7a97d89.png)
3. Goal is to make editable Federal Reimbursement Rates populated with per-defined values

**Comment by pmelendez2** [comment]
@nikolajbaer , Provide link to "Rates / selections are available in CEP Calculator from USDA.", where rates are provided.

**Comment by nikolajbaer** [comment]
https://www.fns.usda.gov/nslp/community-eligibility-provision-resource-center

Direct Link: https://www.fns.usda.gov/sites/default/files/resource-files/CEPEstimatorTool.xlsx

The bottom of the 2nd Tab "Federal Estimator" has a grid of rat types based on different classifications. There is a formula on the third sheet  that I think helps navigate it, but it alll requires Excel (doesn't appear to work in LibreOffice or Google Sheets for me).

**Comment by nikolajbaer** [comment]
Note the current rates might not be up to date to the most recent estimator tool, so worth double checking that.

**Comment by nikolajbaer** [comment]
Additional Note from:
https://www.isbe.net/Documents/cep-plan-implement-guidance1601.pdf

**Comment by nikolajbaer** [comment]
Closing this in favor of #94 , as rate determination is actually not simple and might require changes to include fields at the school level.
