### ISSUE TITLE
Clean up Git repo

### ISSUE THREAD

**Issue by pmelendez2** [opensandiego/mealscount-backend#65]
Git repo needs to be cleaned up:
1. Merge 'validate' branch to 'master', set 'master' as default, using 'master' ts the convention usage 
2. Delete 'dead' branches, some branches have not been worked on in over 2 years.

Doing the above cleanup will allow a good foundation for following changes.

**Comment by nikolajbaer** [comment]
I have centralized on the new standard of "main" and made this the primary branch as new convention. Closing this!
